### ISSUE TITLE
NZFurs Login

### ISSUE THREAD

**Issue by NZSmartie** [NZFurs/FurCoNZ#1]
Automake Lets encrypt certificate with Azure functions and configure it the server to use the certificate

**Comment by NZSmartie** [comment]
Need to clean up the certificate retrieval code. It's pretty much an ugly hack.

And check for an updated certificate on keyvault periodically

**Comment by NZSmartie** [comment]
😡 @tcfox

**Comment by TCFox** [comment]
Handled in https://github.com/NZFurs/Login

Hard requirement for launch.

**Comment by TCFox** [comment]
Website soft-launched. Still some minor things missing and the design needs a bit of love but we largely got it going for now.
