### ISSUE TITLE
Content - Page Management

### ISSUE THREAD

**Issue by NZSmartie** [NZFurs/FurCoNZ#11]
Landing and other static content. 

templates for those pages and stuff

**Comment by TCFox** [comment]
Moving requirement for this to be dynamic to vNext. For now we can get away with static HTML inside `.cshtml` pages to get us going for 2020.

Still need to get this done, in particular:

* [x] Clone all pages currently on furconz.org.nz
* [x] Add in Mailchimp forms
* [x] Skin these to fit the theme
* [x] Add good markup for the form pages
* [x] Add Parental Consent form

**Comment by Glutnix** [comment]
#95 #94 fix most of this

**Comment by TCFox** [comment]
Need a parental contact form still, but this is largely done.

Future content will be tracked in other issues as they are only required after release.
