### ISSUE TITLE
No content on page when Stripe payment is completed/cancelled

### ISSUE THREAD

**Issue by TCFox** [NZFurs/FurCoNZ#113]
Need to know what we want to be displayed when:

* Customer pays for their order via Stripe
* Customer cancels their payment on the Stripe page or it is declined

Currently it's just a blank page with a single "👍" or "👎" emoji.

**Comment by NZSmartie** [comment]
This is just a static landing page. It just needs to display a friendly message saying the payment is being processed and they'll be emailed upon success.

This is because payments happen asynchronously in an ihostedservice

**Comment by NZSmartie** [comment]
👍 has become:
![image](https://user-images.githubusercontent.com/1032029/68078801-c94bde80-fe42-11e9-8776-36ac079e3db5.png)

and 👎 has become:
![image](https://user-images.githubusercontent.com/1032029/68078800-be914980-fe42-11e9-9f3c-1480cca00770.png)
