### ISSUE TITLE
Stripe payments requires use of 'unsafe-inline' CSP directive

### ISSUE THREAD

**Issue by TCFox** [NZFurs/FurCoNZ#117]
As per #53, CSP has been implemented however Stripe payments use inline JS. Currently setting this to allow unsafe inline JS while this is resolved so we can launch.

**Comment by NZSmartie** [comment]
This issue also extends to the admin panel and needs to be tested

**Comment by NZSmartie** [comment]
Fixed in 2dc2fe4
