### ISSUE TITLE
A user who has completed purchase of a ticket wishes to indicate their preference to room in the same cabin as their friends

### ISSUE THREAD

**Issue by NZSmartie** [NZFurs/FurCoNZ#15]
Leave this as a text field. if we have time, look at building a invite group system

**Comment by TCFox** [comment]
Feedback from Nimble/Kendra is that a text field is preferred.

* Even at ~120 attendees it's easy enough to sort them manually
* An invite system is technically expensive to implement
* It's a privacy risk (you can see attendees without buying a ticket)
* It's not logically feasible (can't add people who haven't signed up)

**Comment by TCFox** [comment]
Closing this as this currently meets requirements.
