### ISSUE TITLE
Ticketing System - Ticket Types

### ISSUE THREAD

**Issue by NZSmartie** [NZFurs/FurCoNZ#6]
there will be 

 - different ticket types
 - Information per ticket (photos, text, pricing)
 - Age bracket requirement

**Comment by TCFox** [comment]
Still need to enhance this with additional information about each ticket beyond just a sentence. Need to ask Kendra what these will be, and work with @Glutnix to enhance the current page to display this.

Can just be a simple string containing HTML for now.

**Comment by TCFox** [comment]
#119 tracks remaining technincal debt
